import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import PageHeader from "./components/PageHeader";
import PageFooter from "./components/PageFooter";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Kane Svelan Web Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body suppressHydrationWarning>
        <ThemeProvider attribute="class">
          <Theme>
            <PageHeader/>
            <main>{children}</main>
            <PageFooter />
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
